name: ken_burns_slideshow
description: A Flutter Package that slideshows images along with Ken Burns effects
version: 1.0.0
homepage: https://github.com/rafidgotit/ken_burns_slideshow

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: '>=3.3.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
